import {getDevice,saveDevice} from './device-store.js';
import {createTransport} from './transport.js';
import {avatarColors,formatAgo,sanitizeName} from './utils.js';
import {reconnect} from './reconnect.js';
import {smartBotManager} from './bot-manager.js';
import {reserveRoleForSeat,ensureParticipantReservations,getRoleReservations} from './assign-role.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let device=getDevice(),transport=createTransport(),room=null,unsub=null;
const screens=$$('.screen');
function show(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));window.FFAudio?.setContext('lobby')}
function status(msg,cls=''){const el=$('#lobbyStatus');if(!el)return;el.textContent=msg;el.className=`status-line ${cls}`}
function paintAvatar(el,seed){if(!el)return;const [a,b]=avatarColors(seed);el.style.setProperty('--avatar-a',a);el.style.setProperty('--avatar-b',b);el.textContent='●'}
function renderDevice(){device=getDevice();$('#deviceName').textContent=device.displayName;$('#deviceIdLabel').textContent=`Device ${device.deviceId.slice(-8)}`;paintAvatar($('#deviceAvatar'),device.avatarSeed);$('#connectionPill').textContent=transport.mode==='backend'?'Google Apps Script backend':'Local test transport'}
function meInRoom(){return room?.players?.find(p=>p.isSelf)||room?.players?.find(p=>p.deviceId===room?.selfParticipantId)||room?.players?.find(p=>p.deviceId===device.deviceId)}
function isHost(){const me=meInRoom();return !!me?.isHost||room?.hostId===me?.participantId||room?.hostId===device.deviceId}
async function refreshRoom(){if(!room)return;try{room=await transport.getRoom(room.code);renderRoom()}catch(e){status(e.message,'error')}}
function renderRoom(){
  if(!room)return;const me=meInRoom(),host=isHost(),managed=smartBotManager.managedParticipantIds(room.code);
  $('#roomName').textContent=room.name;$('#roomCode').textContent=room.code;$('#roomVisibility').textContent=room.isPublic?'Public room':'Private room';$('#playerCount').textContent=`${room.players.length}/${room.maxPlayers}`;$('#readySummary').textContent=`${room.players.filter(p=>p.ready).length} ready`;
  $$('.host-only').forEach(x=>x.classList.toggle('hidden',!host));const pub=$('[data-action="toggle-public"]');if(pub)pub.textContent=room.isPublic?'Make Private':'Make Public';const ready=$('[data-action="toggle-ready"]');if(ready)ready.textContent=me?.ready?'Not Ready':'Ready';
  const list=$('#playerList');list.innerHTML='';for(const p of room.players){const row=$('#playerTemplate').content.firstElementChild.cloneNode(true);paintAvatar($('.avatar',row),p.avatarSeed);$('strong',row).textContent=`Player ${p.seat||'?'} · ${p.displayName}`;const smart=managed.has(p.participantId||p.deviceId);const tags=[];if(p.isHost||p.deviceId===room.hostId)tags.push('Host');if(p.isSelf)tags.push('You');if(p.kind==='bot'||smart)tags.push('Role Bot');$('small',row).textContent=tags.join(' • ')||'Player';const rb=$('.ready-badge',row);rb.textContent=p.ready?'READY':'WAITING';rb.classList.toggle('ready',p.ready);const kick=$('.host-kick',row);kick.hidden=!host||p.isSelf||typeof transport.kick!=='function';if(!kick.hidden)kick.addEventListener('click',()=>act(()=>transport.kick({code:room.code,deviceId:device.deviceId,targetId:p.deviceId})));list.append(row)}
  const smartCount=[...managed].filter(id=>room.players.some(p=>(p.participantId||p.deviceId)===id)).length;
  $('#roomSettings').innerHTML=`<dt>Visibility</dt><dd>${room.isPublic?'Public':'Private'}</dd><dt>Ready check</dt><dd>Required</dd><dt>Backend phase</dt><dd>${room.phase||room.status}</dd><dt>Seats</dt><dd>${room.players.length}/${room.maxPlayers}</dd><dt>Role bots</dt><dd>${smartCount} managed · empty seats fill on Start</dd>`;
  const feed=$('#lobbyFeed');feed.innerHTML='';for(const m of room.messages||[]){const p=document.createElement('p');p.className='feed-line';p.innerHTML=`<strong></strong> <span></span> <small></small>`;$('strong',p).textContent=m.displayName;$('span',p).textContent=m.text;$('small',p).textContent=` · ${formatAgo(m.createdAt)}`;feed.append(p)}feed.scrollTop=feed.scrollHeight;
  status(host?'You are host. Empty seats will use the new role-aware bots when you start.':'Waiting for host.');if(room.status==='starting')launchGame();
}
async function act(fn){try{const out=await fn();if(out?.code&&room&&out.code!==room.code){room=out;reconnect.save(room.code)}else if(out?.players)room=out;if(room)renderRoom();return out}catch(e){status(e.message,'error');throw e}}
function bindRoomEvents(){unsub?.();unsub=transport.onEvent(async e=>{if(!room)return;if(e.code===room.code||e.oldCode===room.code||e.type==='room.updated')await refreshRoom()});if(transport.mode==='backend'&&transport.connectRoom)transport.connectRoom(room.code,device.deviceId)}
async function enterRoom(r){room=r;reconnect.save(r.code);const me=(r.players||[]).find(p=>p.isSelf)||(r.players||[]).find(p=>p.deviceId===device.deviceId);if(me){const id=me.participantId||me.deviceId||device.deviceId;try{reserveRoleForSeat(r.code,id,{seat:me.seat||1,targetPlayers:r.targetPlayers||r.maxPlayers||8,source:'app-create/join'})}catch{}}bindRoomEvents();show('lobby');renderRoom()}
function launchGame(){window.FFAudio?.setContext('silent');const url=new URL('assets/code/frenzy.html',location.href);url.searchParams.set('room',room.code);url.searchParams.set('device',device.deviceId);setTimeout(()=>location.href=url.toString(),200)}
async function fillRoleBotsBeforeStart(){if(!room||transport.mode!=='backend')return[];const target=Math.min(Number(room.targetPlayers||room.maxPlayers||8),Number(room.maxPlayers||12));if(room.players.length>=target)return[];status('Adding bots for missing reserved roles…');const participants=(room.players||[]).map(p=>({id:p.participantId||p.deviceId,seat:p.seat,kind:p.kind}));ensureParticipantReservations(room.code,participants,target);const added=await smartBotManager.fillMissingRoles({code:room.code,target,currentParticipants:participants});await refreshRoom();return added}
async function loadPublic(){const box=$('#publicGames');box.innerHTML='<div class="join-preview">Loading…</div>';try{let rooms=await transport.publicRooms();const q=sanitizeName($('#publicSearch').value,36).toLowerCase(),seats=Number($('#publicSeats').value||0);rooms=rooms.filter(r=>(!q||r.name.toLowerCase().includes(q))&&(r.maxPlayers-r.playerCount>=seats));box.innerHTML='';if(!rooms.length){box.innerHTML='<div class="join-preview empty">No public rooms are visible right now.</div>';return}for(const r of rooms){const el=document.createElement('article');el.className='public-room';el.innerHTML='<div><h3></h3><p></p></div><button class="primary compact">Join</button>';$('h3',el).textContent=r.name;$('p',el).textContent=`${r.playerCount}/${r.maxPlayers} • Code ${r.code}`;$('button',el).onclick=()=>act(async()=>{const x=await transport.joinRoom({code:r.code,device});await enterRoom(x);return x});box.append(el)}}catch(e){box.innerHTML=`<div class="join-preview error">${e.message}</div>`}}
$$('[data-action]').forEach(b=>b.addEventListener('click',async()=>{const a=b.dataset.action;if(a==='home')show('home');if(a==='open-create')show('create');if(a==='open-join')show('join');if(a==='open-public'){show('public');loadPublic()}if(a==='refresh-public')loadPublic();if(a==='edit-device'){const d=$('#deviceDialog');d.showModal();d.querySelector('[name=displayName]').value=device.displayName;d.querySelector('[name=avatarSeed]').value=device.avatarSeed}if(a==='copy-code'&&room){await navigator.clipboard?.writeText(room.code);status('Room code copied.','success')}if(a==='toggle-ready'&&room){const me=meInRoom();await act(()=>transport.setReady({code:room.code,deviceId:device.deviceId,ready:!me?.ready}))}if(a==='toggle-public'&&room)await act(()=>transport.setPublic({code:room.code,deviceId:device.deviceId,isPublic:!room.isPublic}));if(a==='leave-room'&&room){if(isHost())await smartBotManager.removeRoomBots(room.code);await transport.leaveRoom({code:room.code,deviceId:device.deviceId});transport.disconnect?.();room=null;reconnect.clear();show('home')}if(a==='start-game'&&room){await fillRoleBotsBeforeStart();await act(()=>transport.start({code:room.code,deviceId:device.deviceId}))}}));
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act(async()=>{const r=await transport.createRoom({device,name:f.get('roomName'),maxPlayers:f.get('maxPlayers'),isPublic:f.get('isPublic')==='on'});await enterRoom(r);return r})});
$('#joinForm [name=roomCode]').addEventListener('input',e=>{const v=e.target.value.replace(/\D/g,'').slice(0,6);e.target.value=v;const box=$('#joinPreview');box.classList.remove('error');box.textContent=v.length===6?'Code ready · press Join Game.':'Enter a six-digit code.'});
$('#joinForm').addEventListener('submit',async e=>{e.preventDefault();const code=new FormData(e.currentTarget).get('roomCode').replace(/\D/g,'');await act(async()=>{const r=await transport.joinRoom({code,device});await enterRoom(r);return r})});
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const input=e.currentTarget.elements.message,message=input.value;if(!message.trim())return;input.value='';await act(()=>transport.chat({code:room.code,device,message}))});
$('#publicSearch').addEventListener('input',loadPublic);$('#publicSeats').addEventListener('change',loadPublic);
$('#deviceDialog').addEventListener('close',e=>{if(e.target.returnValue!=='save')return;const f=new FormData($('#deviceForm'));device=saveDevice({...device,displayName:f.get('displayName'),avatarSeed:f.get('avatarSeed')});renderDevice()});
renderDevice();window.FFAudio?.setContext('lobby');const last=reconnect.load();if(last){try{const r=await transport.joinRoom({code:last.code,device});await enterRoom(r)}catch{reconnect.clear()}}
