(()=>{
'use strict';
const BASE='../images/';
const LOGO='../images/frenzy_logo.png';
const META={
  BANDIT:{name:'Bandit',variety:'Sable / Black Sable',team:'Bandit side',icon:'🐾',wake:'1 × d12',actionDie:'d6 only for Raider tiebreak',summary:'Know the starting Bandit roster. The earliest starting-Bandit wake becomes the historical Raider.',rules:['Starting Bandits privately know the Bandit roster and Raider identity.','The Raider taps the Minnow Treats during the theft hour.','Card movement never transfers or erases historical Raider status.','Morning Business may include bluffing about time, Treat State, or role claims.'],images:['01_Bandit_Sable_Black_Sable_01.jpg','02_Bandit_Sable_Black_Sable_02.jpg','03_Bandit_Sable_Black_Sable_03.jpg','04_Bandit_Sable_Black_Sable_04.jpg']},
  DOOKER:{name:'Dooker',variety:'Silver Mitt',team:'Business side',icon:'⇄',wake:'3 unique d12s',actionDie:'No routine d6',summary:'Three wakes: observe, Glimpse one player’s current allegiance at that moment, then inspect one Hammock card and optionally Trip it onto a player.',rules:['First chronological wake is observation only.','Second wake may Glimpse one player’s current allegiance at that exact moment: Bandit-aligned or Not Bandit-aligned; later movement can make the fact stale.','Third wake views exactly one Hammock card and may swap it with one player current card.','The displaced player card is not revealed as part of Trip.'],images:['05_Dooker_Silver_Mitt_01.jpg']},
  ITCHY:{name:'Itchy',variety:'Cinnamon',team:'Business side',icon:'◔',wake:'1 d12 · 2 if activated',actionDie:'Setup d6: 5–6 activates',summary:'Roll d6 first. On 5–6, gain a second unique wake and a partial Raider clue.',rules:['d6 1–4: Too Itchy, no special clue.','d6 5–6: Ears Up, gain a second unique d12 wake.','Activated clue is deliberately partial: usually two candidates containing exactly one Raider.','If no legal decoy exists, the clue must be explicitly marked degraded; never silently present a one-name pair.'],images:['06_Itchy_Cinnamon_01.jpg']},
  TROUBLE:{name:'Trouble',variety:'Champagne',team:'Business side · may convert',icon:'↔',wake:'1 × d12',actionDie:'No routine d6',summary:'Blind-swap two other Current Cards. If awake for the theft, become In On It before swapping and learn the historical Raider.',rules:['Choose two distinct other players; never self.','You know which positions were exchanged, not the card identities.','If present for the Raider theft, you become a Bandit-side accomplice before the swap and learn the historical Raider identity.','Accomplice status follows you even if cards later move.'],images:['07_Trouble_Champagne_01.jpg']},
  BUSINESS:{name:'Business',variety:'Warm Sable Roan',team:'Business side',icon:'•••',wake:'1 × d12',actionDie:'No routine d6',summary:'Observe Treat State and co-wakers. If you wake genuinely alone, inspect exactly one wake result from one chosen player.',rules:['You are the ordinary evidence role.','Every wake shows authorized Treat State and co-wakers.','If you wake alone, you may privately inspect exactly one randomly selected wake result belonging to one chosen player; you do not learn their full schedule.','Simple claims are intentionally easy for Bandits to imitate, so compare multiple facts.'],images:Array.from({length:14},(_,i)=>`${String(8+i).padStart(2,'0')}_Business_Roan_${String(i+1).padStart(2,'0')}.jpg`)},
  SNUGGLER:{name:'Snuggler',variety:'Chocolate',team:'Business side',icon:'∞',wake:'1 × d12',actionDie:'No routine d6',summary:'Before Hour 1, bond two other players. If one is caught, the partner can be Bond-Revealed in results without becoming an extra Paw Point catch.',rules:['Choose two players before Hour 1.','Bonded players privately learn each other identity, not each other role.','The bond follows the players and survives card swaps.','If one bonded player is caught by Paw Point or a valid Hunt Mark, the partner is Bond-Revealed in results; Bond-Reveal is not itself a capture and cannot satisfy the Raider win condition.'],images:['22_Snuggler_Chocolate_01.jpg']},
  HUNTER:{name:'Hunter',variety:'Blaze',team:'Business side · may convert',icon:'⌖',wake:'2 unique d12s',actionDie:'Overlap d6: 1–2 converts',summary:'Two wakes. First Bandit overlap can trigger one d6 conversion check; if still loyal, set one conditional Hunt Mark.',rules:['Hunter and Guardian recognize each other before Hour 1.','The first wake overlap with any starting Bandit triggers one private d6.','1–2 converts Hunter to Bandit side; 3–6 stays loyal. Guardian is never told.','A loyal Hunter later sets one Hunt Mark that only triggers if Hunter is caught.'],images:['23_Hunter_Blaze_01.jpg']},
  GUARDIAN:{name:'Guardian',variety:'Dark-Eyed White',team:'Business side',icon:'⬡',wake:'1 × d12',actionDie:'No routine d6',summary:'Know the starting Hunter. Immediately before vote resolution, protect one other player once.',rules:['Guardian and Hunter recognize each other before Hour 1.','Guardian never learns whether Hunter later converted.','Protection cannot target self.','Protection removes one other player from Paw Point capture eligibility for that resolution. Votes cast on that player remain part of replay but do not set the top eligible capture total.'],images:['24_Guardian_Dark-Eyed_White_01.jpg']}
};
const upper=v=>String(v||'').trim().toUpperCase();
const $=id=>document.getElementById(id);
function hashSeed(value){let h=2166136261;for(const ch of String(value||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function roleImage(role,seed='1'){const id=upper(role),m=META[id];if(!m)return '';const list=m.images;return BASE+list[hashSeed(seed)%list.length]}
function meta(role,fallback={}){const id=upper(role);const m=META[id]||{};return {id,name:fallback.name||m.name||id||'Unknown',variety:fallback.variety||fallback.pattern||m.variety||'',team:fallback.team||m.team||'',summary:fallback.summary||m.summary||'',icon:fallback.icon||m.icon||'🐾',wake:fallback.wake||m.wake||'',actionDie:fallback.actionDie||m.actionDie||'',rules:Array.isArray(fallback.rules)?fallback.rules:(m.rules||[]),image:roleImage(id,fallback.seed||id)}}
function cardBack(label='Hidden card',sub='FERRET FRENZY'){
  const el=document.createElement('div');el.className='ff-card ff-card-back';el.innerHTML=`<div class="ff-card-back-art"><img src="${LOGO}" alt=""></div><div class="ff-card-copy"><strong>${escapeHtml(label)}</strong><small>${escapeHtml(sub)}</small></div>`;return el;
}
function roleCard(role,{seed='1',title='',compact=false,revealLabel='',backendMeta=null}={}){
  const m=meta(role,{...(backendMeta||{}),seed});const el=document.createElement('article');el.className='ff-card ff-role-card'+(compact?' compact':'');el.dataset.role=m.id;
  const details=m.rules.map(x=>`<li>${escapeHtml(x)}</li>`).join('');
  el.innerHTML=`<div class="ff-card-image-wrap"><span class="ff-role-icon" aria-hidden="true">${escapeHtml(m.icon)}</span><img class="ff-card-image" src="${m.image}" alt="${escapeHtml(m.name)} role card"></div><div class="ff-card-copy">${title?`<span class="ff-card-kicker">${escapeHtml(title)}</span>`:''}<strong>${escapeHtml(m.name)}</strong><span>${escapeHtml(m.variety)}</span>${!compact?`<div class="ff-card-statline"><b>${escapeHtml(m.icon)} ${escapeHtml(m.wake)}</b><b>${escapeHtml(revealLabel||m.team)}</b></div><small>${escapeHtml(m.summary)}</small><span class="ff-action-die">${escapeHtml(m.actionDie)}</span><details class="ff-card-rules"><summary>Full role rules</summary><ul>${details}</ul></details>`:''}</div>`;return el;
}
function playerBack(p,{selected=false,labelPrefix='Player'}={}){const label=`${labelPrefix} ${p?.seat||'?'}${p?.displayName?' · '+p.displayName:''}`;const isBot=p?.kind==='BOT'||/^Ferret Bot\b/i.test(String(p?.displayName||''));const el=cardBack(label,isBot?'BOT FERRET':'HIDDEN ROLE');el.classList.add('ff-player-card');el.dataset.participantId=p?.id||'';if(selected)el.classList.add('selected');return el}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
let lastRevealKey='';
function revealKey(state){return `${state?.game?.id||''}:${state?.me?.startingRole||''}`}
function seenKey(state){return 'ff:role-card-seen:'+revealKey(state)}
function hasAcknowledged(state){const key=revealKey(state);if(!key||key.endsWith(':'))return false;try{return localStorage.getItem(seenKey(state))==='1'}catch{return key===lastRevealKey}}
function shouldAutoReveal(state){const role=upper(state?.me?.startingRole);if(!role||!META[role])return false;const phase=upper(state?.game?.phase);if(!['PREP','NIGHT'].includes(phase))return false;const key=revealKey(state);try{return localStorage.getItem(seenKey(state))!=='1'}catch{return key!==lastRevealKey}}
function acknowledge(state){const key=revealKey(state);lastRevealKey=key;try{localStorage.setItem(seenKey(state),'1')}catch{};$('roleRevealOverlay')?.setAttribute('hidden','');window.dispatchEvent(new CustomEvent('ff-role-card-acknowledged',{detail:{gameId:state?.game?.id||'',role:upper(state?.me?.startingRole)}}))}
function renderReveal(state){const overlay=$('roleRevealOverlay'),slot=$('roleRevealCard');if(!overlay||!slot)return;const me=state?.me||{},role=upper(me.startingRole);if(!role||!META[role]){overlay.hidden=true;return}slot.innerHTML='';slot.append(roleCard(role,{seed:me.seat||me.id,title:'YOUR STARTING CARD',backendMeta:me.role,revealLabel:me.isRaider?'RAIDER · BANDIT SIDE':(me.role?.team||META[role].team)}));if(shouldAutoReveal(state))overlay.hidden=false}
function renderDock(state){const dock=$('roleCardDock');if(!dock)return;const me=state?.me||{},role=upper(me.startingRole);dock.innerHTML='';if(!role||!META[role]){dock.hidden=true;return}dock.hidden=false;dock.append(roleCard(role,{seed:me.seat||me.id,compact:true,backendMeta:me.role}));dock.title='Your starting role card';}
function renderPrivate(state){const slot=$('privateRoleCardSlot');if(slot){slot.innerHTML='';const me=state?.me||{};if(me.startingRole)slot.append(roleCard(me.startingRole,{seed:me.seat||me.id,title:'STARTING CARD',backendMeta:me.role}));}
  const final=$('privateFinalCardSlot');if(final){final.innerHTML='';const phase=upper(state?.game?.phase);if(phase==='RESULTS'&&state?.me?.currentCard)final.append(roleCard(state.me.currentCard,{seed:'final-'+(state.me.seat||state.me.id),title:'FINAL CARD'}));else final.append(cardBack('Final card','REVEALED AT RESULTS'));}
}
function renderLobbyRoster(state){const box=$('lobbyRoster');if(!box)return;box.innerHTML='';const ps=state?.participants||[];for(const p of ps){const card=playerBack(p);if(p.id===state?.me?.id)card.classList.add('is-you');if(p.isHost)card.classList.add('is-host');box.append(card)}if(!ps.length)box.innerHTML='<div class="readout">Waiting for players…</div>'}
function renderResults(state){const box=$('resultsCards'),summary=$('resultsSummary');if(!box)return;box.innerHTML='';const participants=state?.participants||[],res=state?.results||{};for(const p of participants){const role=p.currentCard||p.startingRole;const wrap=document.createElement('article');wrap.className='ff-result-player'+(p.caught?' caught':'');const c=roleCard(role,{seed:'result-'+(p.seat||p.id),compact:false,title:`PLAYER ${p.seat||'?'} · ${p.displayName||'Ferret'}`,revealLabel:p.isRaider?'RAIDER':(p.allegiance?`${p.allegiance} SIDE`:'')});wrap.append(c);const note=document.createElement('div');note.className='ff-result-note';note.textContent=`Started: ${prettyRole(p.startingRole)}${p.currentCard&&p.currentCard!==p.startingRole?` · Final: ${prettyRole(p.currentCard)}`:''}${p.caught?' · CAUGHT':(p.bondRevealed?' · BOND-REVEALED · NOT CAUGHT':'')}`;wrap.append(note);box.append(wrap)}
  if(summary){const winner=String(res.primaryWinner||'').toUpperCase();summary.textContent=winner?`${winner==='BUSINESS'?'Business caught the Raider':'Bandits protected the Raider'}.`:'Round complete.'}
}
function prettyRole(role){const id=upper(role);return META[id]?.name||id||'Unknown'}
function sync(state){renderReveal(state);renderDock(state);renderPrivate(state);renderLobbyRoster(state);if(upper(state?.game?.phase)==='RESULTS')renderResults(state)}
function transientReveal(role,{title='REVEALED CARD',message=''}={}){const box=$('cardToast'),slot=$('cardToastSlot'),note=$('cardToastNote');if(!box||!slot)return;slot.innerHTML='';slot.append(roleCard(role,{seed:'transient-'+Date.now(),title}));if(note)note.textContent=message;box.hidden=false;clearTimeout(transientReveal._t);transientReveal._t=setTimeout(()=>{box.hidden=true},5000)}
function bind(){document.querySelectorAll('[data-ack-role-card]').forEach(b=>b.addEventListener('click',()=>{const st=window.FFNetwork?.getState?.();if(st)acknowledge(st);else $('roleRevealOverlay')?.setAttribute('hidden','')}));$('roleCardDock')?.addEventListener('click',()=>window.FerretFrenzyShell?.openPanel?.('privateInfo'));$('cardToastClose')?.addEventListener('click',()=>{$('cardToast').hidden=true})}
const api={META,meta,roleImage,roleCard,cardBack,playerBack,sync,renderResults,transientReveal,acknowledge,hasAcknowledged,prettyRole};window.FFCards=api;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
