import {normalizeRevision3State} from './revision3-normalizer.js';
import {smartBotManager} from './bot-manager.js';

const ENDPOINT=window.FF_BACKEND_URL||'https://script.google.com/macros/s/AKfycbyAShO3c_FLVqp-fisabNx_DMuLD0UYMPygU22_jQfpLjIs796fgsJPo3viZq5FGeYd1A/exec';
const TOKEN_KEY='ff:guest-token:v2',GAME_PREFIX='ff:game-id:',NARRATOR_PREFIX='[[FF_NARRATOR_V1]]',CHANNEL_TAG='[[FF_CH:',SYSTEM_TAG='[[FF_SYS:';
const CHAT_CHANNELS=['burrow','evidence','claims','paw-point','narrator'];
const params=new URLSearchParams(location.search),room=(params.get('room')||params.get('code')||'').replace(/\D/g,'').slice(0,6);
let gameId=params.get('gameId')||localStorage.getItem(GAME_PREFIX+room)||'',token=localStorage.getItem(TOKEN_KEY)||localStorage.getItem('ff:guest-token:v1')||'';
let state=null,afterSeq=0,pollTimer=0,polling=false,voteChoice='',voteAutoOpened=false,actionSelections=[],hourStartAt=0,hourStartHour=0,advanceRetry=0,lastPromptKey='',resultsOpened=false,chatSending=false,banditCueUntil=0,quickClaimSending=false,lastSocialPhase='',lastChatMessages=[],turnSending=false;
let activeChannel=localStorage.getItem('ff:chat-channel:'+room)||'burrow';if(!CHAT_CHANNELS.includes(activeChannel))activeChannel='burrow';
let turnState={mode:false,floorId:'',queue:[]};
const $=id=>document.getElementById(id);
const upper=v=>String(v||'').trim().toUpperCase();
const gameRef=()=>gameId?{gameId}:{code:room};

async function call(action,data={}, {requiresToken=true}={}){
  if(!ENDPOINT)throw new Error('Backend endpoint is not configured.');
  if(requiresToken&&!token)throw new Error('Guest session is missing. Return to the lobby and rejoin the burrow.');
  const payload={action,data:{...data}};if(requiresToken)payload.data.guestToken=token;
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);
  try{
    const res=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload),cache:'no-store',redirect:'follow',signal:controller.signal});
    if(!res.ok)throw new Error(`Backend HTTP ${res.status}`);
    const env=await res.json();if(env?.ok===false){const e=env.error||{};throw Object.assign(new Error(e.message||'Backend error'),{code:e.code||'API_ERROR',details:e.details,status:e.status})}
    return Object.prototype.hasOwnProperty.call(env||{},'data')?env.data:env;
  }catch(err){if(err?.name==='AbortError')throw new Error('Ferret Frenzy backend timed out.');throw err}finally{clearTimeout(timeout)}
}
function seatLabel(p){return `Player ${p?.seat||'?'}${p?.displayName?' · '+p.displayName:''}`}
function prettyRole(role){return window.FFCards?.prettyRole?.(role)||String(role||'').replaceAll('_',' ')}
function factText(f){
  if(typeof f==='string')return f;if(!f)return '—';const t=upper(f.type);
  if(t==='BANDIT_ROSTER')return `Starting Bandits: ${(f.participants||[]).map(x=>x.displayName||x.participantId).join(', ')}`;
  if(t==='RAIDER_IDENTITY')return `Raider: ${f.displayName||f.participantId}`;
  if(t==='ITCHY_CHECK')return `Itchy d6: ${f.roll} · ${f.activated?'EARS UP (extra wake)':'TOO ITCHY'}`;
  if(t==='HUNTER_CONVERSION')return `Hunter d6: ${f.roll} · ${f.converted?'converted to Bandit side':'remained Business side'}`;
  if(t==='DOOKER_GLIMPSE')return `Glimpse${f.observedAtHour||f.hour?` at Hour ${f.observedAtHour||f.hour}`:''}: ${f.displayName||f.participantId} · current allegiance was ${String(f.result||'').replaceAll('_',' ')} at that moment`;
  if(t==='DOOKER_HAMMOCK_PEEK')return `Hammock ${Number(f.hammockIndex)+1}: ${prettyRole(f.role)}`;
  if(t==='DOOKER_TRIP')return `Trip: Hammock ${Number(f.hammockIndex)+1} card moved to ${f.displayName||f.targetId}`;
  if(t==='TROUBLE_SWAP')return `Blind swap locked: ${seatLabel((state?.participants||[]).find(p=>p.id===f.targetAId))} ↔ ${seatLabel((state?.participants||[]).find(p=>p.id===f.targetBId))}`;
  if(t==='BUSINESS_WAKE_INSPECTION'){const h=Number(f.inspectedWakeHour||f.wakeHour||f.resultHour||f.result||0);return `${f.displayName||f.participantId}: one inspected wake result${h?` · Hour ${h}`:''} (not their full schedule)`;}
  if(t==='SNUGGLE_BOND')return `Snuggle-Bonded with ${f.displayName||f.participantId}`;
  if(t==='SNUGGLER_BOND_SET')return 'Your Snuggle Bond pair is locked.';
  if(t==='HUNTER_RECOGNITION')return `Starting Hunter: ${f.displayName||f.participantId}`;
  if(t==='GUARDIAN_RECOGNITION')return `Starting Guardian: ${f.displayName||f.participantId}`;
  if(t==='HUNT_MARK')return `Hunt Mark: ${f.displayName||f.participantId}`;
  if(t==='GUARDIAN_PROTECTION')return `Protected: ${f.displayName||f.participantId}`;
  if(t==='TROUBLE_CONVERTED')return `In On It · converted during Hour ${f.hour||'?'}${f.raiderDisplayName||f.raiderName||f.raiderId?` · historical Raider learned: ${f.raiderDisplayName||f.raiderName||f.raiderId}`:''}`;
  if(t==='ITCHY_PARTIAL_CLUE'){const names=(f.candidates||[]).map(x=>x.displayName||x.participantId).filter(Boolean);return f.degraded===true||names.length!==2?`Degraded Itchy clue: ${names.join(' / ')||'no valid two-player pair could be formed'}`:`Exactly one of these two is the historical Raider: ${names.join(' / ')}`;}
  if(t==='ITCHY_TIMING_CLUE')return `Degraded Itchy clue · Raider timing: ${f.range==='HOURS_1_6'?'Hours 1–6':'Hours 7–12'}`;
  return `${String(f.type||'FACT').replaceAll('_',' ')}${f.displayName?': '+f.displayName:''}${f.hour?': Hour '+f.hour:''}`;
}
function promptText(prompt,stateNow=state){
  const kind=upper(prompt?.kind),type=upper(prompt?.type),purpose=upper(prompt?.purpose);
  if(kind==='ROLL'){
    if(purpose==='ITCHY_CHECK')return 'Pre-Game Setup · Itchy: select /1/ d6 and flick the joystick. 5–6 activates Ears Up.';
    if(purpose==='WAKE')return 'Pre-Game Setup · wake roll: select /2/ d12 and flick the joystick. Duplicate wake hours reroll automatically.';
    if(purpose==='RAIDER_TIE')return 'Pre-Game Setup · Bandit Raider tiebreak: select /1/ d6 and flick. Lowest unique tied-Bandit result becomes Raider.';
    if(purpose==='HUNTER_CONVERSION')return 'Hunter overlap: select /1/ d6 and flick. 1–2 converts; 3–6 remains loyal.';
    return `Private ${String(prompt?.die||'die').toUpperCase()} roll required.`;
  }
  if(kind==='ACTION'){
    const map={SNUGGLER_BOND:'Snuggler: choose two other players to become Snuggle-Bonded before Hour 1.',DOOKER_GLIMPSE:'Dooker Glimpse: choose one other player to learn current allegiance at this exact moment: BANDIT-ALIGNED or NOT BANDIT-ALIGNED. Later movement can make that fact stale.',DOOKER_PEEK_HAMMOCK:'Dooker Trip setup: inspect one of the three face-down Hammock cards.',DOOKER_TRIP:'Dooker Trip: optionally place the inspected Hammock card onto one player.',TROUBLE_SWAP:'Trouble: choose two other players. Their current cards swap blindly.',BUSINESS_INSPECT:'Business woke genuinely alone: optionally inspect exactly one randomly selected wake result from one other player, not their whole schedule.',HUNTER_MARK:'Hunter: secretly place one Hunt Mark on another player.',GUARDIAN_PROTECT:'Guardian: protect one other player before Paw Point resolution.'};
    return map[type]||'A private role action is waiting. Press X.';
  }
  if(kind==='SLEEP')return `Night Lock · Hour ${stateNow?.game?.currentHour||'?'} · you are asleep.`;
  if(kind==='CHAT')return 'Morning Business: discuss claims, wake times, co-wakers, and Treat State.';
  if(kind==='VOTE')return 'Paw Point: select exactly one player and lock your vote.';
  if(kind==='WAIT')return prompt?.label||'Waiting for the other ferrets.';
  return '';
}
function applyPrivate(s){const me=s?.me||{},obs=me.observations||[];FerretFrenzyGame.setPrivateInfo({role:me.role?.name||prettyRole(me.startingRole)||'—',wakeSchedule:(me.wakeHours||[]).map(h=>`Hour ${h}`),treatStates:obs.map(o=>`Hour ${o.hour}: ${o.treatChangedDuringWindow?'PRESENT → MISSING':o.treatStateBefore||'—'}`),coWakers:obs.map(o=>`Hour ${o.hour}: ${(o.coWakers||[]).map(x=>x.displayName||x.participantId).join(', ')||'alone'}`),facts:(me.privateFacts||[]).map(factText)});const prompt=me.actionPrompt||{};FerretFrenzyGame.setRoleActionAvailable(prompt.kind==='ACTION',prompt.type||prompt.label||'Role action')}
function applyScene(){if(window.FFMinnowHitbox){window.FFMinnowHitbox.update(state);return}const phase=upper(state?.game?.phase),scene=$('gameScene'),hud=$('treatHud'),text=$('treatHudText'),missing=['MORNING','VOTE','RESULTS'].includes(phase);if(scene){scene.src=missing?'../images/Minnow Treats crime scene-2.png':'../images/Aurora-lit ferret treats bookshelf-1.png';scene.alt=missing?'Aurora-lit ferret shelf after the Minnow Treats were stolen, marked as a crime scene':'Aurora-lit ferret shelf with the Minnow Treats present'}hud?.classList.toggle('missing',missing);if(text)text.textContent=missing?'TREATS MISSING':'TREATS PRESENT'}
function phaseAudio(phase){if(phase==='VOTE')window.FFAudio?.setContext('vote');else if(phase==='MORNING')window.FFAudio?.setContext('discussion');else if(phase==='PREP'||phase==='NIGHT')window.FFAudio?.setContext('night');else window.FFAudio?.setContext('silent')}
function socialStep(phase){
  const order=['MORNING','VOTE','RESULTS'],idx=order.indexOf(phase);
  document.querySelectorAll('[data-social-step]').forEach((el,i)=>{el.classList.toggle('active',i===idx);el.classList.toggle('complete',idx>i)});
}
function messageTime(m){const raw=m.createdAt||m.sentAt||m.timestamp||m.at;if(!raw)return'';const d=new Date(raw);if(Number.isNaN(d.getTime()))return'';return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});}
function safeChannel(id){id=String(id||'burrow').toLowerCase();return CHAT_CHANNELS.includes(id)?id:'burrow'}
function encodeChannel(id){return `[[FF_CH:${safeChannel(id).toUpperCase()}]]`}
function encodeSystem(command){return `[[FF_SYS:${String(command||'').replace(/\]\]/g,'')}]]`}
function parseMessage(m){let text=String(m?.text||''),narrator=false,channel='burrow',system='';if(text.startsWith(NARRATOR_PREFIX)){narrator=true;text=text.slice(NARRATOR_PREFIX.length)}const cm=text.match(/^\[\[FF_CH:([A-Z0-9_-]+)\]\]/i);if(cm){channel=safeChannel(cm[1]);text=text.slice(cm[0].length)}const sm=text.match(/^\[\[FF_SYS:([^\]]+)\]\]/i);if(sm){system=sm[1];text=text.slice(sm[0].length)}return{raw:m,text:text.trim(),narrator,channel,system,senderId:String(m?.senderId||m?.participantId||'')}}
function hostParticipantId(){return String(state?.game?.hostParticipantId||(state?.participants||[]).find(p=>p.isHost)?.id||'')}
function participantName(id){return(state?.participants||[]).find(p=>String(p.id)===String(id))?.displayName||'a player'}
function systemText(pm){const bits=String(pm.system||'').split(':'),kind=bits[0],action=bits[1],arg=bits.slice(2).join(':');if(kind!=='TURN')return'';if(action==='MODE')return arg==='ON'?'Turn Mode enabled. Raise Paw to request the floor.':'Turn Mode disabled. Open discussion restored.';if(action==='REQUEST')return`${participantName(pm.senderId)} raised a paw.`;if(action==='CANCEL')return`${participantName(pm.senderId)} lowered their paw.`;if(action==='GRANT')return`${participantName(arg)} has the floor.`;if(action==='YIELD')return`${participantName(pm.senderId)} ended their turn.`;if(action==='CLEAR')return'The current turn ended. Waiting for the next raised paw.';return''}
function computeTurnState(parsed){const hostId=hostParticipantId(),ts={mode:false,floorId:'',queue:[]};for(const pm of parsed){if(!pm.system.startsWith('TURN:'))continue;const bits=pm.system.split(':'),action=bits[1],arg=bits.slice(2).join(':');const hostCommand=String(pm.senderId)===hostId;if(action==='MODE'&&hostCommand){ts.mode=arg==='ON';if(!ts.mode){ts.floorId='';ts.queue=[]}}else if(action==='REQUEST'&&ts.mode){if(pm.senderId&&pm.senderId!==ts.floorId&&!ts.queue.includes(pm.senderId))ts.queue.push(pm.senderId)}else if(action==='CANCEL'){ts.queue=ts.queue.filter(id=>id!==pm.senderId)}else if(action==='GRANT'&&hostCommand){ts.mode=true;ts.floorId=arg;ts.queue=ts.queue.filter(id=>id!==arg)}else if(action==='YIELD'&&pm.senderId===ts.floorId){ts.floorId=''}else if(action==='CLEAR'&&hostCommand){ts.floorId=''}}return ts}
function canPlayerChat(){const phase=upper(state?.game?.phase);if(!['MORNING','VOTE'].includes(phase))return false;if(activeChannel==='narrator')return false;if(!turnState.mode)return true;return String(turnState.floorId)===String(state?.me?.id||'')}
function updateComposerAccess(){const input=$('discussionInput'),send=$('discussionSendButton'),form=$('discussionForm'),quick=$('quickClaim'),phase=upper(state?.game?.phase),writablePhase=['MORNING','VOTE'].includes(phase),can=canPlayerChat();if(form)form.hidden=!writablePhase;if(input){input.disabled=!can;input.placeholder=activeChannel==='narrator'?'#narrator is read-only; the game narrator posts here.':turnState.mode&&!can?'Turn Mode is on — Raise Paw and wait for the floor.':`Message #${activeChannel}`;}if(send)send.disabled=!can;if(form)form.classList.toggle('turn-muted',writablePhase&&!can);if(quick)quick.hidden=!writablePhase||activeChannel==='narrator';const sendClaim=$('quickClaimSendButton'),draft=$('quickClaimDraftButton');if(sendClaim&&!can)sendClaim.disabled=true;if(draft&&!can)draft.disabled=true}
function updateTurnControls(ts){turnState=ts;const host=isHost(),meId=String(state?.me?.id||''),queued=ts.queue.includes(meId),mine=String(ts.floorId)===meId,badge=$('turnModeBadge'),status=$('turnFloorStatus'),modeBtn=$('turnModeButton'),raise=$('raisePawButton'),next=$('nextTurnButton'),end=$('endTurnButton'),queue=$('turnQueueList');if(badge){badge.textContent=ts.mode?'TURN MODE':'OPEN';badge.classList.toggle('locked',ts.mode)}if(status)status.textContent=!ts.mode?'Open discussion: anyone may type.':ts.floorId?`${participantName(ts.floorId)} has the floor. Other players are text-muted until their turn.`:'Turn Mode is active. Raise Paw to enter the queue.';const turnPhase=['MORNING','VOTE'].includes(upper(state?.game?.phase));if(modeBtn){modeBtn.hidden=!host;modeBtn.disabled=!turnPhase;modeBtn.textContent=ts.mode?'Disable Turn Mode':'Enable Turn Mode'}if(raise){raise.disabled=!turnPhase||!ts.mode||mine;raise.textContent=queued?'✋ Lower Paw':'✋ Raise Paw'}if(next){next.hidden=!host;next.disabled=!turnPhase||!ts.mode||!ts.queue.length;next.textContent=ts.floorId?'Next Turn':'Grant Next Turn'}if(end){end.disabled=!turnPhase||!ts.mode||!ts.floorId||(!host&&!mine);end.textContent=host&&!mine&&ts.floorId?'End Current Turn':'End Turn'}if(queue){queue.innerHTML='';if(!ts.queue.length)queue.innerHTML='<li>None</li>';else ts.queue.forEach(id=>{const li=document.createElement('li');li.textContent=participantName(id);queue.append(li)})}updateComposerAccess();window.dispatchEvent(new CustomEvent('ff-turn-state',{detail:{mode:ts.mode,floorId:ts.floorId,queue:ts.queue.slice()}}))}
function updateChannelUI(parsed=[]){for(const id of CHAT_CHANNELS){const btn=document.querySelector(`[data-chat-channel="${id}"]`);btn?.classList.toggle('active',id===activeChannel);const suffix=id==='paw-point'?'PawPoint':id[0].toUpperCase()+id.slice(1),counter=$('channelCount'+suffix);if(counter)counter.textContent=String(parsed.filter(m=>m.channel===id&&!m.system).length)}const label=$('discussionChannelLabel');if(label)label.textContent=`#${activeChannel} · public to every player`;const title=$('discussionTitle');if(title)title.textContent=activeChannel==='burrow'?'Morning Business':`#${activeChannel}`;updateComposerAccess()}
function setActiveChannel(id){activeChannel=safeChannel(id);try{localStorage.setItem('ff:chat-channel:'+room,activeChannel)}catch{}renderDiscussion(lastChatMessages)}
function renderDiscussion(messages=[]){const box=$('discussionMessages');if(!box)return;lastChatMessages=messages.slice();box.innerHTML='';const parsed=messages.map(parseMessage);updateTurnControls(computeTurnState(parsed));updateChannelUI(parsed);const hostId=hostParticipantId();const visible=parsed.filter(pm=>pm.system.startsWith('TURN:')||pm.channel===activeChannel);const count=$('discussionCount');if(count)count.textContent=`${visible.filter(m=>!m.system).length} message${visible.filter(m=>!m.system).length===1?'':'s'}`;if(!visible.length){box.innerHTML=`<div class="discussion-empty">No messages in #${activeChannel} yet.</div>`;return}for(const pm of visible){const m=pm.raw,isNarrator=pm.narrator&&!!hostId&&pm.senderId===hostId,isSystem=!!pm.system,displayText=isSystem?systemText(pm):pm.text;if(isSystem&&!displayText)continue;const row=document.createElement('article'),isBot=!isNarrator&&!isSystem&&(upper(m.senderKind||m.kind)==='BOT'||/^Ferret Bot\b/i.test(String(m.senderName||''))),isSelf=!isNarrator&&!isSystem&&!!state?.me?.id&&pm.senderId===String(state.me.id);row.className='discussion-message'+(isNarrator?' narrator':'')+(isBot?' bot':'')+(isSelf?' self':'')+(isSystem?' system':'');const head=document.createElement('div');head.className='discussion-message-head';const name=document.createElement('strong');name.textContent=isSystem?'Turn Floor':isNarrator?'Ferret Frenzy Narrator':(m.senderName||'Ferret Frenzy');const stamp=document.createElement('time');stamp.textContent=messageTime(m);const channelChip=document.createElement('span');channelChip.className='channel-chip';channelChip.textContent=isSystem?'global':`#${pm.channel}`;head.append(name,channelChip,stamp);const body=document.createElement('p');body.textContent=displayText;row.append(head,body);box.append(row)}box.scrollTop=box.scrollHeight}
async function refreshChat(){if(!state||!['MORNING','VOTE','RESULTS','LOBBY'].includes(upper(state.game?.phase)))return;try{const r=await call('chat.list',{...gameRef(),limit:200});renderDiscussion(r?.messages||[])}catch{}}
function isHost(){const me=state?.me;if(me?.isHost===true)return true;return !!(state?.participants||[]).find(p=>p.id===me?.id)?.isHost}
function publicLockedVoteCount(){const g=state?.game||{},candidates=[g.lockedVoteCount,g.votesLocked,g.voteProgress?.locked,g.voteStatus?.lockedCount];for(const n of candidates){const x=Number(n);if(Number.isFinite(x)&&x>=0)return x}return null}
function renderVote(){
 const phase=upper(state?.game?.phase),vote=$('pawVote');if(!vote)return;socialStep(phase);vote.hidden=phase!=='VOTE';$('openVotingButton').hidden=!(phase==='MORNING'&&isHost());$('discussionPhaseNote').textContent=phase==='MORNING'?'Morning Business: compare evidence and claims before the host opens Paw Point voting. Claims are not automatically verified.':phase==='VOTE'?'Paw Point is open. Chat stays open while everyone talks, types, selects one player, and locks once.':phase==='RESULTS'?'Paw Point is resolved. The discussion remains available for review.':'Discussion opens after Hour 12.';updateComposerAccess();if(phase!=='VOTE')return;
 const me=state.me||{},prompt=me.actionPrompt||{},box=$('voteCandidates');box.innerHTML='';const guardianPending=prompt.kind==='ACTION'&&upper(prompt.type)==='GUARDIAN_PROTECT';
 for(const p of (state.participants||[]).filter(x=>x.id!==me.id)){const b=document.createElement('button');b.type='button';b.className='vote-candidate';b.dataset.targetId=p.id;b.setAttribute('role','radio');b.setAttribute('aria-checked',String(voteChoice===p.id));const card=window.FFCards?.playerBack?.(p,{selected:voteChoice===p.id})||document.createTextNode(seatLabel(p));b.append(card);const check=document.createElement('span');check.className='vote-check';check.setAttribute('aria-hidden','true');check.textContent='✓';b.append(check);if(voteChoice===p.id)b.classList.add('selected');b.disabled=guardianPending||!!me.voteLocked;b.addEventListener('click',()=>selectVote(p.id));box.append(b)}
 const selected=(state.participants||[]).find(p=>p.id===voteChoice);$('lockVoteButton').disabled=guardianPending||!voteChoice||!!me.voteLocked;$('lockVoteButton').textContent=me.voteLocked?'Paw Point Locked':voteChoice?`Lock ${seatLabel(selected||{})}`:'Lock Paw Point';$('clearVoteButton').disabled=guardianPending||!!me.voteLocked;$('voteStatus').textContent=guardianPending?'Guardian protection must be locked before your Paw Point. Press X.':me.voteLocked?'Your Paw Point is locked. You cannot change it; discussion remains visible while the others finish.':voteChoice?`Selected ${seatLabel(selected||{})}. Locking is final for this vote.`:'Choose exactly one player. Your selection stays private until the server resolves the Paw Point.';const locked=publicLockedVoteCount();$('voteProgress').textContent=me.voteLocked?(locked==null?'YOUR VOTE LOCKED':`${locked} LOCKED`):(locked==null?'PRIVATE SELECTION':`${locked} LOCKED`);if(!voteAutoOpened){voteAutoOpened=true;window.FerretFrenzyShell?.openPanel('chat')}
}
function legalVoteTarget(id){return !!id&&String(id)!==String(state?.me?.id||'')&&(state?.participants||[]).some(p=>String(p.id)===String(id))}
function selectVote(id){if(state?.me?.voteLocked||!legalVoteTarget(id))return;voteChoice=id;renderVote()}
async function lockVote(){if(state?.me?.voteLocked)return;if(!legalVoteTarget(voteChoice)){voteChoice='';if($('voteStatus'))$('voteStatus').textContent='Choose one other active player. Self-votes are not legal.';renderVote();return}try{$('lockVoteButton').disabled=true;const next=await call('vote.cast',{...gameRef(),targetId:voteChoice});applyState(next)}catch(e){$('voteStatus').textContent=e.message;renderVote()}}
function confirmFocusedVote(){if(upper(state?.game?.phase)!=='VOTE'||state?.me?.voteLocked)return false;const active=document.activeElement;if(active?.classList?.contains('vote-candidate')){selectVote(active.dataset.targetId);return true}if(voteChoice){lockVote();return true}return false}
async function beginVoting(){try{const next=await call('vote.begin',gameRef());applyState(next)}catch(e){$('discussionPhaseNote').textContent=e.message}}
function makeRoleChoice(p,label){const b=document.createElement('button');b.type='button';b.className='role-target ff-role-target-card';b.dataset.id=p.id;const card=window.FFCards?.playerBack?.(p)||null;if(card)b.append(card);else b.textContent=label;return b}
function buildRoleAction(){const prompt=state?.me?.actionPrompt||{},panel=$('roleActionTargets'),confirm=$('roleActionConfirm'),pass=$('roleActionPass');if(!panel)return false;panel.innerHTML='';actionSelections=[];$('roleActionTitle').textContent=prompt.type?prompt.type.replaceAll('_',' '):'Role Action';$('roleActionPrompt').textContent=promptText(prompt);$('roleActionStatus').textContent='This choice is private and sent only to the authoritative game state.';pass.hidden=!prompt.optional;confirm.disabled=true;if(prompt.kind!=='ACTION')return false;
 const addButton=(b,id,choose)=>{b.onclick=()=>{if(choose>1){if(actionSelections.includes(id))actionSelections=actionSelections.filter(x=>x!==id);else if(actionSelections.length<choose)actionSelections.push(id)}else actionSelections=[id];[...panel.children].forEach(x=>x.classList.toggle('selected',actionSelections.includes(x.dataset.id)));confirm.disabled=actionSelections.length!==choose};panel.append(b)};
 const choose=Math.max(1,Number(prompt.choose||1)),type=upper(prompt.type),otherPlayerOnly=new Set(['SNUGGLER_BOND','DOOKER_GLIMPSE','DOOKER_TRIP','TROUBLE_SWAP','BUSINESS_INSPECT','HUNTER_MARK','GUARDIAN_PROTECT']);if(type==='DOOKER_PEEK_HAMMOCK'){for(let i=0;i<Number(prompt.hammockSlots||3);i++){const b=document.createElement('button');b.type='button';b.className='role-target ff-role-target-card';b.dataset.id=String(i);b.append(window.FFCards?.cardBack?.(`Hammock ${i+1}`,'FACE DOWN')||document.createTextNode(`Hammock ${i+1}`));addButton(b,String(i),1)}}else for(const p of (state.participants||[]).filter(x=>!(prompt.excludeSelf||otherPlayerOnly.has(type))||x.id!==state.me.id))addButton(makeRoleChoice(p,seatLabel(p)),p.id,choose);return true}
function openRoleAction(){if(upper(state?.game?.phase)==='PREP'&&state?.me?.startingRole&&!window.FFCards?.hasAcknowledged?.(state)){const banner=$('rollResult');if(banner)banner.textContent='Review your dealt role card before using a Pre-Game role action.';return false}if(!buildRoleAction())return false;window.FerretFrenzyShell?.openPanel('roleAction');return true}
async function submitRoleAction(pass=false){const prompt=state?.me?.actionPrompt||{};if(prompt.kind!=='ACTION')return;let data={...gameRef(),type:prompt.type};if(pass)data.pass=true;else if(upper(prompt.type)==='TROUBLE_SWAP'){data.targetAId=actionSelections[0];data.targetBId=actionSelections[1]}else if(upper(prompt.type)==='SNUGGLER_BOND'){data.targetAId=actionSelections[0];data.targetBId=actionSelections[1];data.targetIds=actionSelections.slice(0,2)}else if(upper(prompt.type)==='DOOKER_PEEK_HAMMOCK')data.hammockIndex=Number(actionSelections[0]);else data.targetId=actionSelections[0];try{const r=await call('game.action',data);if(r?.action?.role)window.FFCards?.transientReveal?.(r.action.role,{title:'DOOKER HAMMOCK PEEK',message:`Hammock ${Number(r.action.hammockIndex)+1}`});if(r?.state)applyState(r.state);else if(r?.game)applyState(r);else await poll();window.FerretFrenzyShell?.closePanel?.('roleAction');if(['MORNING','VOTE'].includes(upper(state?.game?.phase)))window.FerretFrenzyShell?.openPanel?.('chat')}catch(e){$('roleActionStatus').textContent=e.message}}
function truthyActivity(v){if(v===true||v===1)return true;const t=upper(v);return ['TRUE','ACTIVE','BANDIT','BANDIT_SIDE','RAIDER','ACCOMPLICE','IN_ON_IT'].includes(t)}
function locallyManagedBanditSideActive(s){
  const hour=Number(s?.game?.currentHour||0);
  for(const bot of smartBotManager.instances?.values?.()||[]){const bs=bot?.lastState;if(upper(bs?.game?.phase)!=='NIGHT'||Number(bs?.game?.currentHour||0)!==hour||upper(bs?.me?.actionPrompt?.kind)==='SLEEP')continue;const me=bs?.me||{},role=upper(me.startingRole||me.role?.id),facts=Array.isArray(me.privateFacts)?me.privateFacts:[];if(role==='BANDIT'||/BANDIT/.test(upper(me.role?.team||me.role?.alignment||me.allegiance)))return true;if(facts.some(f=>upper(f?.type)==='TROUBLE_CONVERTED'||(upper(f?.type)==='HUNTER_CONVERSION'&&f?.converted===true)))return true;}
  return false;
}
function banditSideActivityHint(s){
  const g=s?.game||{},me=s?.me||{},hour=Number(g.currentHour||0);
  const direct=[g.banditOrAccompliceActive,g.banditSideActive,g.banditActivityActive,g.accompliceActive,g.raiderActive,g.threatActive,g.activity?.banditSide,g.activity?.banditOrAccomplice,g.nightActivity?.banditSide,me.audioCue,me.sleepCue?.banditSide,me.sleepCue?.banditOrAccomplice];
  if(direct.some(truthyActivity))return true;
  const roles=[];
  for(const list of [g.activeRoles,g.activeRoleIds,g.nightActivity?.activeRoles,g.activity?.activeRoles])if(Array.isArray(list))roles.push(...list);
  for(const a of [...(Array.isArray(g.activeActors)?g.activeActors:[]),...(Array.isArray(g.nightActivity?.activeActors)?g.nightActivity.activeActors:[])])roles.push(a?.role,a?.alignment,a?.allegiance,a?.status);
  if(roles.some(v=>/(BANDIT|RAIDER|ACCOMPLICE|IN[_ ]?ON[_ ]?IT)/i.test(String(v||''))))return true;
  const activeIds=[...(g.activeParticipantIds||[]),...(g.awakeParticipantIds||[]),...(g.pendingParticipantIds||[])].map(String);
  if(g.raiderId&&activeIds.includes(String(g.raiderId)))return true;
  const accompliceIds=[...(g.accompliceIds||[]),...(g.banditSideIds||[])].map(String);if(activeIds.some(id=>accompliceIds.includes(id)))return true;
  if(Date.now()<banditCueUntil)return true;
  if(locallyManagedBanditSideActive(s))return true;
  return false;
}
function applySleepLock(s){
  const phase=upper(s?.game?.phase),prompt=s?.me?.actionPrompt||{},sleeping=phase==='NIGHT'&&prompt.kind==='SLEEP',chitter=sleeping&&banditSideActivityHint(s);const lock=$('sleepLock');
  if(lock)lock.hidden=!sleeping;document.documentElement.classList.toggle('ff-sleeping',sleeping);document.body.classList.toggle('ff-sleeping',sleeping);window.FFAudio?.setChitterActive?.(chitter);
}
function syncStartControls(){const phase=upper(state?.game?.phase),host=isHost();document.querySelectorAll('[data-start-game]').forEach(b=>{const show=phase==='LOBBY'&&host;b.hidden=!show;b.disabled=!show});const reset=document.querySelector('[data-reset-game]');if(reset)reset.hidden=phase!=='LOBBY';const pause=$('pauseButton');if(pause){pause.hidden=!(phase==='NIGHT'&&host);pause.disabled=!(phase==='NIGHT'&&host)}}
async function fillBotsToTarget(target){let participants=(state.participants||[]).slice();if(state.game.allowBots===false||participants.length>=target)return participants;await smartBotManager.fillMissingRoles({code:room,target,currentParticipants:participants});const refreshed=await call('game.state',gameRef());if(refreshed?.game){applyState(refreshed);participants=refreshed.participants||participants}return participants}
async function startGame(){if(!state?.game)throw new Error('Game state is not connected yet.');const phase=upper(state.game.phase);if(phase!=='LOBBY')return state;if(!isHost())throw new Error('Only the host can start this Ferret Frenzy round.');const target=Math.max(4,Math.min(10,Number(state.game.targetPlayers||state.game.maxPlayers||6))),fillEmpty=state.game.allowBots!==false&&state.game.autoFillBots!==false;if(fillEmpty){$('networkStatus').textContent='LOBBY · HOST · filling empty seats with Ferret Frenzy v3 bots…';await fillBotsToTarget(target)}$('networkStatus').textContent='PRE-GAME · HOST · backend shuffling and randomly dealing private role cards…';const next=await call('game.start',{...gameRef(),force:true});applyState(next);smartBotManager.resumeRoom(room).catch(err=>console.warn('Ferret Frenzy v3 bot start:',err));return next}
function processEvents(events=[]){for(const ev of events){const type=upper(ev.type),h=Number(ev?.payload?.hour||0),at=Date.parse(ev.createdAt||'');if((type==='BURROW_HOUR'||type==='NIGHT_STARTED')&&Number.isFinite(at)){if(type==='BURROW_HOUR'){hourStartAt=at;hourStartHour=h||state?.game?.currentHour||1}else if(!hourStartAt){hourStartAt=at;hourStartHour=h||1}}if(/BANDIT_(?:ACTION|WAKE|ACTIVE)|RAIDER_(?:ACTION|WAKE|ACTIVE)|ACCOMPLICE_(?:ACTION|WAKE|ACTIVE)|IN_ON_IT|THEFT|MINNOW_STOLEN|TROUBLE_CONVERTED|HUNTER_CONVERSION/.test(type+' '+upper(ev?.payload?.cue||'')))banditCueUntil=Date.now()+6500;if(type==='MORNING_BUSINESS'){hourStartAt=0;hourStartHour=0;banditCueUntil=0}}}
function syncDicePrompt(s){const prompt=s?.me?.actionPrompt||{},phase=upper(s?.game?.phase);if(phase==='PREP'&&s?.me?.startingRole&&!window.FFCards?.hasAcknowledged?.(s)){FerretFrenzyGame.setRoleActionAvailable(false,'Review role card');window.FerretFrenzyShell?.setRequiredDie?.('','');const banner=$('rollResult');if(banner&&!window.FerretDice?.isRolling?.())banner.textContent='Pre-Game Step 1 · review your dealt role card, then continue.';lastPromptKey='ROLE_CARD';return;}FerretFrenzyGame.setRoleActionAvailable(prompt.kind==='ACTION',prompt.type||prompt.label||'Role action');const die=prompt.kind==='ROLL'?String(prompt.die||'').toLowerCase():'';window.FerretFrenzyShell?.setRequiredDie?.(die,prompt.purpose||'');const msg=promptText(prompt,s);if(msg&&prompt.kind!=='SLEEP'){const banner=$('rollResult');if(banner&&!window.FerretDice?.isRolling?.())banner.textContent=msg}
 const key=`${phase}:${s?.game?.currentHour||0}:${prompt.kind||''}:${prompt.type||prompt.purpose||''}`;if(prompt.kind==='ACTION'&&key!==lastPromptKey){lastPromptKey=key;if(['MORNING','VOTE'].includes(phase)){const note=$('discussionPhaseNote');if(note)note.textContent=(phase==='VOTE'?'Paw Point is open. Chat stays open while you type. ':'Morning Business is open. ')+`Private ${String(prompt.type||'role action').replaceAll('_',' ')} is ready; press X when you want to make that private choice.`;}else setTimeout(()=>openRoleAction(),250)}else if(prompt.kind!=='ACTION')lastPromptKey=key}
function openPhasePanels(phase){if(['MORNING','VOTE'].includes(phase)){if(lastSocialPhase!==phase){lastSocialPhase=phase;window.FerretFrenzyShell?.openPanel('chat')}}else lastSocialPhase='';if(phase==='RESULTS'&&!resultsOpened){resultsOpened=true;window.FerretFrenzyShell?.openPanel('results')}}
function applyState(s){if(!s?.game)return;s=normalizeRevision3State(s);state=s;gameId=s.game.id||gameId;if(room&&gameId)localStorage.setItem(GAME_PREFIX+room,gameId);const phase=upper(s.game.phase),phaseLabel=phase==='PREP'?'PRE-GAME SETUP':phase;document.getElementById('ferretFrenzyShell').dataset.phase=phase.toLowerCase();if($('roomCodeValue'))$('roomCodeValue').textContent=String(s.game.code||room||'------');$('networkStatus').textContent=`${phaseLabel} · ${isHost()?'HOST':'PLAYER'} · BACKEND LIVE`;$('chatToolLabel').textContent=phase==='VOTE'?'VOTE':phase==='MORNING'?'DISCUSSION':'Discussion';applyPrivate(s);applyScene();phaseAudio(phase);applySleepLock(s);syncStartControls();window.FFCards?.sync?.(s);syncDicePrompt(s);renderVote();FerretFrenzyGame.syncBackendState(s,{hourStartAt:(phase==='NIGHT'&&hourStartHour===Number(s.game.currentHour))?hourStartAt:0,host:isHost()});if(phase==='RESULTS')$('rollResult').textContent=s.results?.primaryWinner?`${String(s.results.primaryWinner).toUpperCase()} SIDE · ROUND COMPLETE`:'ROUND COMPLETE';openPhasePanels(phase);refreshChat()}
async function poll(){if(polling)return;polling=true;try{const r=await call('events.poll',{...gameRef(),afterSeq,limit:200});processEvents(r?.events||[]);afterSeq=Number(r?.latestSeq||afterSeq);applyState(r?.state||r);$('networkStatus').classList.remove('offline')}catch(e){$('networkStatus').textContent='OFFLINE · RETRYING';$('networkStatus').classList.add('offline')}finally{polling=false}}
async function requestRoll(die){if(!state?.game)throw new Error('Game state is not connected.');const prompt=state?.me?.actionPrompt||{};if(prompt.kind!=='ROLL')throw new Error('No private die is required right now.');const required=String(prompt.die||'').toLowerCase();if(required&&die!==required)throw new Error(`${required.toUpperCase()} is required for ${String(prompt.purpose||'this roll').replaceAll('_',' ')}.`);const sides=die==='d12'?12:6;const r=await call('game.roll',{...gameRef(),die:sides});const roll=r?.roll||r,value=Number(roll?.result??roll?.value);if(r?.state)applyState(r.state);if(roll?.rerollRequired)$('rollResult').textContent=`${die.toUpperCase()} → ${value} duplicate · flick again`;return{result:value,duplicate:!!roll?.duplicate,rerollRequired:!!roll?.rerollRequired,purpose:roll?.purpose}}
async function advanceHour(){clearTimeout(advanceRetry);advanceRetry=0;if(!state||!isHost()||upper(state.game?.phase)!=='NIGHT'||FerretFrenzyGame.isPaused())return false;try{FerretFrenzyGame.setWaiting(false);const next=await call('game.advance',gameRef());hourStartAt=0;hourStartHour=0;applyState(next);return true}catch(e){if(e.code==='ACTIONS_PENDING'){FerretFrenzyGame.setWaiting(true);$('rollResult').textContent='Hour complete · waiting for awake ferret actions';advanceRetry=setTimeout(advanceHour,1500);return false}FerretFrenzyGame.setWaiting(false);$('rollResult').textContent='Clock advance error · '+e.message;advanceRetry=setTimeout(advanceHour,3000);return false}}
const QUICK_CLAIM_LABELS={BANDIT:'Bandit',DOOKER:'Dooker',ITCHY:'Itchy',TROUBLE:'Trouble',BUSINESS:'Business',SNUGGLER:'Snuggler',HUNTER:'Hunter',GUARDIAN:'Guardian'};
const QUICK_CLAIM_WAKE_COUNTS={BANDIT:1,DOOKER:3,ITCHY:2,TROUBLE:1,BUSINESS:1,SNUGGLER:1,HUNTER:2,GUARDIAN:1};
const QUICK_CLAIM_FIELDS={
 BANDIT:[],
 DOOKER:[['glimpse','Glimpse target (optional)'],['trip','Trip target (optional)']],
 ITCHY:[['clueA','Partial clue ferret A (optional)'],['clueB','Partial clue ferret B (optional)']],
 TROUBLE:[['swapA','Blind-swap ferret A (optional)'],['swapB','Blind-swap ferret B (optional)'],['raider','Raider identity learned if In On It (optional)']],
 BUSINESS:[['inspect','Wake-hour inspection target (optional)']],
 SNUGGLER:[['bondA','Snuggle Bond ferret A (optional)'],['bondB','Snuggle Bond ferret B (optional)']],
 HUNTER:[['partner','Starting Guardian (optional)'],['mark','Hunt Mark target (optional)']],
 GUARDIAN:[['partner','Starting Hunter (optional)'],['protect','Protected player (optional)']]
};
const HOUR_CHOICES=Array.from({length:12},(_,i)=>[String(i+1),`Hour ${i+1}`]);
function quickClaimPlayers(){return (state?.participants||[]).filter(p=>p.id!==state?.me?.id)}
function quickClaimName(id){const p=(state?.participants||[]).find(x=>String(x.id)===String(id));return p?.displayName||seatLabel(p||{})}
function makeQuickClaimSelect(key,label){const wrap=document.createElement('label');wrap.className='quick-claim-field';const span=document.createElement('span');span.textContent=label;const sel=document.createElement('select');sel.dataset.claimKey=key;const blank=document.createElement('option');blank.value='';blank.textContent='Not saying';sel.append(blank);for(const p of quickClaimPlayers()){const o=document.createElement('option');o.value=p.id;o.textContent=p.displayName||seatLabel(p);sel.append(o)}wrap.append(span,sel);return wrap}
function makeQuickClaimChoice(key,label,choices,{defaultValue=''}={}){const wrap=document.createElement('label');wrap.className='quick-claim-field';const span=document.createElement('span');span.textContent=label;const sel=document.createElement('select');sel.dataset.claimKey=key;const blank=document.createElement('option');blank.value='';blank.textContent='Not saying';sel.append(blank);for(const [value,text] of choices){const o=document.createElement('option');o.value=value;o.textContent=text;sel.append(o)}if(defaultValue)sel.value=defaultValue;wrap.append(span,sel);return wrap}
function renderQuickClaimFields(){
  const role=upper($('quickClaimRole')?.value),box=$('quickClaimTargets'),send=$('quickClaimSendButton'),draft=$('quickClaimDraftButton'),status=$('quickClaimStatus');if(!box)return;box.innerHTML='';
  if(role){
    box.append(makeQuickClaimChoice('claimScope','Role claim describes',[['STARTING','Starting Role'],['CURRENT','Current Card'],['BOTH','Starting Role and Current Card are the same']],{defaultValue:'STARTING'}));
    const wakes=QUICK_CLAIM_WAKE_COUNTS[role]||1;
    for(let i=1;i<=wakes;i++)box.append(makeQuickClaimChoice(`wake${i}`,`Claimed wake ${i}${i===1?'':' (optional)'}`,HOUR_CHOICES));
    box.append(makeQuickClaimChoice('treat1','Treat State at claimed wake 1 (optional)',[['PRESENT','Present'],['MISSING','Missing'],['CHANGED','Present → Missing during that window']]));
    box.append(makeQuickClaimSelect('cowaker1','Co-waker at claimed wake 1 (optional)'));
  }
  for(const [key,label] of QUICK_CLAIM_FIELDS[role]||[])box.append(makeQuickClaimSelect(key,label));
  if(role==='DOOKER'){box.append(makeQuickClaimChoice('glimpseHour','Glimpse hour (optional)',HOUR_CHOICES));box.append(makeQuickClaimChoice('glimpseResult','Glimpse result (optional)',[['BANDIT_ALIGNED','Bandit-aligned'],['NOT_BANDIT_ALIGNED','Not Bandit-aligned']]));}
  if(role==='ITCHY')box.append(makeQuickClaimChoice('itchyActivation','Itchy activation claim (optional)',[['TOO_ITCHY','Too Itchy · d6 1–4'],['EARS_UP','Ears Up · d6 5–6']]));
  if(role==='BUSINESS')box.append(makeQuickClaimChoice('inspectHour','Single inspected wake result (optional)',HOUR_CHOICES));
  const enabled=!!QUICK_CLAIM_LABELS[role]&&['MORNING','VOTE'].includes(upper(state?.game?.phase))&&canPlayerChat();if(send)send.disabled=!enabled;if(draft)draft.disabled=!enabled;if(status)status.textContent=role?`${QUICK_CLAIM_LABELS[role]} selected. Wake/timeline and target menus build a public claim only; nothing here is checked against hidden truth.`:'Choose one of the eight roles. Target menus use the current player and bot usernames.';
}
function quickClaimValues(){const out={};document.querySelectorAll('#quickClaimTargets select[data-claim-key]').forEach(s=>out[s.dataset.claimKey]=s.value);return out}
function buildQuickClaim(){
  const role=upper($('quickClaimRole')?.value);if(!QUICK_CLAIM_LABELS[role])return{ok:false,error:'Choose a role claim first.'};
  const v=quickClaimValues(),name=k=>v[k]?quickClaimName(v[k]):'',same=(a,b)=>v[a]&&v[b]&&v[a]===v[b];
  const wakeKeys=Array.from({length:QUICK_CLAIM_WAKE_COUNTS[role]||1},(_,i)=>`wake${i+1}`),claimedWakes=wakeKeys.map(k=>v[k]).filter(Boolean);
  if(new Set(claimedWakes).size!==claimedWakes.length)return{ok:false,error:'Claimed wake hours must be distinct, or leave duplicate fields blank.'};
  if((role==='DOOKER'&&v.glimpseResult&&!v.glimpse)||(role==='DOOKER'&&v.glimpseHour&&!v.glimpse)||(role==='BUSINESS'&&v.inspectHour&&!v.inspect)||(role==='TROUBLE'&&((v.swapA&&!v.swapB)||(!v.swapA&&v.swapB)||same('swapA','swapB')))||(role==='SNUGGLER'&&((v.bondA&&!v.bondB)||(!v.bondA&&v.bondB)||same('bondA','bondB')))||(role==='ITCHY'&&((v.clueA&&!v.clueB)||(!v.clueA&&v.clueB)||same('clueA','clueB'))))return{ok:false,error:'Complete the matching claim detail, or leave that detail blank.'};
  const scope=v.claimScope==='CURRENT'?'as my Current Card':v.claimScope==='BOTH'?'as both my Starting Role and Current Card':'as my Starting Role';
  let parts=[`I am claiming ${QUICK_CLAIM_LABELS[role]} ${scope}.`];
  if(claimedWakes.length)parts.push(`My wake claim is ${claimedWakes.map(h=>`Hour ${h}`).join(', ')}.`);
  if(v.treat1&&v.wake1){parts.push(v.treat1==='CHANGED'?`At Hour ${v.wake1}, the Minnow Treats changed from PRESENT to MISSING during my window.`:`At Hour ${v.wake1}, the Minnow Treats were ${v.treat1}.`)}
  if(v.cowaker1&&v.wake1)parts.push(`At Hour ${v.wake1}, I woke with ${name('cowaker1')}.`);
  if(role==='DOOKER'){if(v.glimpse)parts.push(`I Glimpsed ${name('glimpse')}'s current allegiance${v.glimpseHour?` at Hour ${v.glimpseHour}`:' at that moment'}${v.glimpseResult?`: ${v.glimpseResult==='BANDIT_ALIGNED'?'Bandit-aligned':'Not Bandit-aligned'}`:''}.`);if(v.trip)parts.push(`My Trip moved the known Hammock card to ${name('trip')}; I did not see the displaced card.`)}
  else if(role==='ITCHY'){if(v.itchyActivation)parts.push(v.itchyActivation==='EARS_UP'?'I am claiming Ears Up activated.':'I am claiming Too Itchy; no special clue activated.');if(v.clueA&&v.clueB)parts.push(`My partial clue pair was ${name('clueA')} / ${name('clueB')}; I am not claiming which one was Raider.`)}
  else if(role==='TROUBLE'){if(v.swapA&&v.swapB)parts.push(`I blind-swapped ${name('swapA')} and ${name('swapB')}; I did not see either card identity.`);if(v.raider)parts.push(`I became In On It and learned ${name('raider')} was the historical Raider.`)}
  else if(role==='BUSINESS'&&v.inspect)parts.push(`I woke alone and inspected one wake result belonging to ${name('inspect')}${v.inspectHour?`: Hour ${v.inspectHour}`:''}; I did not learn their whole schedule.`);
  else if(role==='SNUGGLER'&&v.bondA&&v.bondB)parts.push(`I Snuggle-Bonded ${name('bondA')} and ${name('bondB')}; that bond does not reveal either alignment.`);
  else if(role==='HUNTER'){if(v.partner)parts.push(`I started knowing ${name('partner')} as Guardian; that is a starting-role fact, not proof of my current allegiance.`);if(v.mark)parts.push(`My Hunt Mark was ${name('mark')}.`)}
  else if(role==='GUARDIAN'){if(v.partner)parts.push(`I started knowing ${name('partner')} as Hunter; I am not claiming that proves their current allegiance.`);if(v.protect)parts.push(`I decided to protect ${name('protect')}; protection is separate from my Paw Point.`)}
  return{ok:true,text:parts.join(' ')}
}
function addQuickClaimToDraft(){const built=buildQuickClaim(),status=$('quickClaimStatus'),input=$('discussionInput');if(!built.ok){if(status)status.textContent=built.error;return}if(!input)return;input.value=[input.value.trim(),built.text].filter(Boolean).join(input.value.trim()?' ':'').slice(0,500);updateChatCounter();input.focus();if(status)status.textContent='Claim added to your message. Edit it if you want, then press Send.'}
async function sendQuickClaim(){const built=buildQuickClaim(),status=$('quickClaimStatus'),button=$('quickClaimSendButton');if(!built.ok){if(status)status.textContent=built.error;return}if(quickClaimSending)return;quickClaimSending=true;if(button){button.disabled=true;button.textContent='Sending…'}try{await sendChat(built.text,{channel:'claims'});if(status)status.textContent='Role claim sent to #claims. Chat stays open for discussion and voting.'}catch(e){if(status)status.textContent=e.message}finally{quickClaimSending=false;if(button){button.textContent='Send claim';button.disabled=false}}}
async function sendChat(text,{narrator=false,channel=activeChannel,system=''}={}){let clean=String(text||'').trim();channel=safeChannel(channel);if(chatSending&&!system)return false;if(!narrator&&!system&&!clean)return false;if(!narrator&&!system&&clean.startsWith(NARRATOR_PREFIX))throw new Error('The narrator message marker is reserved for the integrated narrator.');if(!narrator&&!system&&/^\[\[FF_/i.test(clean))throw new Error('Reserved Ferret Frenzy chat markers cannot be typed manually.');if(!narrator&&!system&&!canPlayerChat())throw new Error(activeChannel==='narrator'?'#narrator is read-only.':turnState.mode?'Turn Mode is active. Raise Paw and wait for your turn.':'Chat is not open in this phase.');if(!narrator&&!system&&channel==='narrator')throw new Error('#narrator is reserved for narrator announcements.');let prefix=encodeChannel(channel);if(narrator){clean=clean.replaceAll(NARRATOR_PREFIX,'').trim();if(!clean)return false;prefix=NARRATOR_PREFIX+prefix}if(system)clean=encodeSystem(system);const max=Math.max(0,500-prefix.length);clean=prefix+clean.slice(0,max);if(!system)chatSending=true;const send=$('discussionSendButton');if(send&&!narrator&&!system){send.disabled=true;send.textContent='Sending…'}try{await call('chat.send',{...gameRef(),text:clean});await refreshChat();return true}finally{if(!system)chatSending=false;if(send&&!narrator&&!system){send.textContent='Send';updateComposerAccess()}}}
async function sendNarratorChat(text,{channel='narrator'}={}){return sendChat(text,{narrator:true,channel})}
async function sendTurnSystem(command){if(!['MORNING','VOTE'].includes(upper(state?.game?.phase)))throw new Error('Turn Mode is available only during Morning Business and Paw Point discussion.');if(turnSending)return false;turnSending=true;try{await sendChat('',{channel:'burrow',system:command});return true}finally{turnSending=false}}
async function toggleTurnMode(){if(!isHost())return;await sendTurnSystem(`TURN:MODE:${turnState.mode?'OFF':'ON'}`)}
async function toggleRaisePaw(){const meId=String(state?.me?.id||'');if(!turnState.mode||turnState.floorId===meId)return;await sendTurnSystem(turnState.queue.includes(meId)?'TURN:CANCEL':'TURN:REQUEST')}
async function grantNextTurn(){if(!isHost()||!turnState.mode||!turnState.queue.length)return;await sendTurnSystem(`TURN:GRANT:${turnState.queue[0]}`)}
async function endTurn(){const meId=String(state?.me?.id||'');if(!turnState.mode||!turnState.floorId)return;if(isHost()&&turnState.floorId!==meId)await sendTurnSystem('TURN:CLEAR');else if(turnState.floorId===meId)await sendTurnSystem('TURN:YIELD')}

document.querySelectorAll('[data-chat-channel]').forEach(b=>b.addEventListener('click',()=>setActiveChannel(b.dataset.chatChannel)));$('turnModeButton')?.addEventListener('click',()=>toggleTurnMode().catch(e=>{$('discussionPhaseNote').textContent=e.message}));$('raisePawButton')?.addEventListener('click',()=>toggleRaisePaw().catch(e=>{$('discussionPhaseNote').textContent=e.message}));$('nextTurnButton')?.addEventListener('click',()=>grantNextTurn().catch(e=>{$('discussionPhaseNote').textContent=e.message}));$('endTurnButton')?.addEventListener('click',()=>endTurn().catch(e=>{$('discussionPhaseNote').textContent=e.message}));
const discussionInput=$('discussionInput');function updateChatCounter(){const n=discussionInput?.value?.length||0;const out=$('chatCharCount');if(out)out.textContent=`${n} / 500`}discussionInput?.addEventListener('input',updateChatCounter);$('quickClaimRole')?.addEventListener('change',renderQuickClaimFields);$('quickClaimDraftButton')?.addEventListener('click',addQuickClaimToDraft);$('quickClaimSendButton')?.addEventListener('click',sendQuickClaim);$('quickClaimToggle')?.addEventListener('click',e=>{const body=$('quickClaimBody'),open=!body?.hidden;if(body)body.hidden=open;e.currentTarget.setAttribute('aria-expanded',String(!open));e.currentTarget.textContent=open?'+':'−'});updateChatCounter();renderQuickClaimFields();
$('copyRoomCode')?.addEventListener('click',async()=>{const code=String(state?.game?.code||room||'');try{await navigator.clipboard.writeText(code);$('roomCodeStatus').textContent='Code copied.'}catch{$('roomCodeStatus').textContent='Room code: '+code}});$('discussionForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('discussionInput'),text=input.value;if(!text.trim())return;input.value='';updateChatCounter();try{await sendChat(text)}catch(err){$('discussionPhaseNote').textContent=err.message}});$('lockVoteButton')?.addEventListener('click',lockVote);$('clearVoteButton')?.addEventListener('click',()=>{voteChoice='';renderVote()});$('openVotingButton')?.addEventListener('click',beginVoting);$('roleActionConfirm')?.addEventListener('click',()=>submitRoleAction(false));$('roleActionPass')?.addEventListener('click',()=>submitRoleAction(true));addEventListener('ferret-frenzy-action',e=>{if(e.detail?.type==='burrowHourExpired')advanceHour()});addEventListener('ff-role-card-acknowledged',()=>{if(state){syncDicePrompt(state);const prompt=state?.me?.actionPrompt||{};if(prompt.kind==='ACTION')setTimeout(()=>openRoleAction(),120)}});
window.FFNetwork={requestRoll,openRoleAction,confirmFocusedVote,getState:()=>state,poll,beginVoting,sendChat,sendNarratorChat,sendTurnSystem,setActiveChannel,getActiveChannel:()=>activeChannel,getTurnState:()=>({...turnState,queue:turnState.queue.slice()}),startGame,advanceHour,buildQuickClaim,getRequiredDie:()=>state?.me?.actionPrompt?.kind==='ROLL'?String(state.me.actionPrompt.die||'').toLowerCase():'',call};
if(!token){$('networkStatus').textContent='NO GUEST SESSION · RETURN TO LOBBY';$('rollResult').textContent='Return to lobby.html and join or create a burrow.'}else if(!gameId&&!room){$('networkStatus').textContent='NO ROOM · RETURN TO LOBBY'}else{poll();pollTimer=setInterval(()=>{if(document.visibilityState==='visible')poll()},1200)}
addEventListener('pagehide',()=>{window.FFAudio?.setChitterActive?.(false);if(pollTimer)clearInterval(pollTimer);if(advanceRetry)clearTimeout(advanceRetry)});
