(()=>{
'use strict';
const MARKER='[[FF_NARRATOR_V1]]';
const $=id=>document.getElementById(id);
const ui={
  phase:$('narratorPhase'),hour:$('narratorHour'),seat:$('narratorSeat'),currentLine:$('narratorCurrentLine'),lineKind:$('narratorLineKind'),speakerDot:$('narratorSpeakerDot'),
  repeat:$('narratorRepeat'),pause:$('narratorPause'),stop:$('narratorStop'),test:$('narratorTestVoice'),log:$('narratorLog'),clearLog:$('narratorClearLog'),
  headphones:$('narratorHeadphones'),publicAudio:$('narratorPublicAudio'),autoSpeak:$('narratorAutoSpeak'),autoChat:$('narratorAutoChat'),
  voiceStatus:$('narratorVoiceStatus'),soundStatus:$('narratorSoundStatus'),connectionStatus:$('narratorConnectionStatus'),chatForm:$('narratorChatForm'),chatInput:$('narratorChatInput'),chatSend:$('narratorChatSend'),chatChannel:$('narratorChatChannel'),sendCurrent:$('narratorSendCurrent')
};
if(!ui.currentLine)return;
const state={paused:false,current:null,voices:[],selectedVoice:null,lastPublicKey:'',lastPromptKey:'',lastFactKeys:new Set(),factsSeeded:false,lastSpoken:'',lastKind:'',lastShared:'',lastSharedKey:'',sentChatKeys:new Set(),chatStoreKey:'',processing:false,soundLevel:.45};
const cap=s=>String(s||'').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const upper=s=>String(s||'').trim().toUpperCase();
const roleName=role=>({BANDIT:'Bandit',DOOKER:'Dooker',ITCHY:'Itchy',TROUBLE:'Trouble',BUSINESS:'Business',SNUGGLER:'Snuggler',HUNTER:'Hunter',GUARDIAN:'Guardian'})[role]||'your role';
function participants(){return state.current?.participants||[]}
function namesForIds(ids){return(ids||[]).map(id=>participants().find(p=>String(p.id)===String(id))?.displayName||'a player').join(' and ')}
function isHost(){const s=state.current,me=s?.me||{};if(me.isHost===true)return true;return!!(s?.participants||[]).find(p=>String(p.id)===String(me.id))?.isHost}
function canChatPhase(){return['LOBBY','MORNING','VOTE','RESULTS'].includes(upper(state.current?.game?.phase))}
function setStatus(message,error=false){if(!ui.connectionStatus)return;ui.connectionStatus.textContent=message;ui.connectionStatus.classList.toggle('error',error)}
function currentSoundLevel(){const v=Number(window.FFAudio?.getMaster?.());return Number.isFinite(v)?Math.max(0,Math.min(1,v)):state.soundLevel}
function syncSound(level=currentSoundLevel()){
  state.soundLevel=Math.max(0,Math.min(1,Number(level)||0));
  if(state.soundLevel===0&&'speechSynthesis'in window)window.speechSynthesis.cancel();
  if(ui.soundStatus)ui.soundStatus.textContent=state.soundLevel===0?'Narrator speech muted by the Ferret Frenzy sound toggle. Chat text remains visible.':`Narrator speech follows the game sound control · ${Math.round(state.soundLevel*100)}% volume.`;
}
function speak(line){
  const level=currentSoundLevel();syncSound(level);
  if(level<=0){setStatus('Narrator speech is muted by the Ferret Frenzy sound toggle.');return false}
  if(!line||!('speechSynthesis'in window)||!window.SpeechSynthesisUtterance)return false;
  window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(line);if(state.selectedVoice)u.voice=state.selectedVoice;u.lang='en-US';u.rate=1.04;u.pitch=1.48;u.volume=level;window.speechSynthesis.speak(u);return true
}
function loadVoices(){if(!('speechSynthesis'in window))return;state.voices=window.speechSynthesis.getVoices();const english=state.voices.filter(v=>/^en([_-]|$)/i.test(v.lang)),feminine=/(female|woman|aria|jenny|samantha|ava|zoe|allison|serena|karen|moira|fiona|tessa|susan|victoria|hazel|libby|sonia|sara|natasha|joanna|kendra|kimberly|salli|ivy|june)/i;state.selectedVoice=english.find(v=>feminine.test(v.name))||english[0]||null;if(ui.voiceStatus)ui.voiceStatus.textContent=state.selectedVoice?`Voice: ${state.selectedVoice.name} (${state.selectedVoice.lang}) · bright high-register delivery.`:'Using the device default speech voice.';syncSound()}
function logLine(line,kind){const empty=ui.log?.querySelector('.narrator-empty');if(empty)empty.remove();if(!ui.log)return;const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'});text.textContent=line;li.append(time,text);if(kind==='private'){const tag=document.createElement('span');tag.className='narrator-private-tag';tag.textContent='PRIVATE';li.append(tag)}ui.log.prepend(li);while(ui.log.children.length>40)ui.log.lastElementChild.remove()}
function say(line,kind='shared',key=''){if(!line)return;state.lastSpoken=line;state.lastKind=kind;if(kind==='shared'){state.lastShared=line;state.lastSharedKey=key||state.lastSharedKey}ui.currentLine.textContent=line;ui.lineKind.textContent=kind==='private'?'PRIVATE ROLE INSTRUCTION':'SHARED NARRATOR';ui.speakerDot.style.color=kind==='private'?'#ffd884':'#9fe7b4';ui.repeat.disabled=false;ui.sendCurrent.disabled=kind!=='shared'||!isHost()||!canChatPhase();logLine(line,kind);if(ui.autoSpeak.checked&&!state.paused&&(kind==='shared'?ui.publicAudio.checked:ui.headphones.checked))speak(line);if(kind==='shared'&&ui.autoChat.checked&&isHost()&&canChatPhase())postNarratorChat(line,key,'narrator').catch(err=>setStatus(`Narrator chat could not post: ${err.message}`,true))}
function privatePrompt(game,me){const p=me.actionPrompt||{},role=me.startingRole;if(p.kind==='ROLL'){if(p.purpose==='ITCHY_CHECK')return'Private setup: roll the d6 shown in Ferret Frenzy. Five or six activates a second Burrow Hour. Then complete the required d12 wake roll or rolls. Keep every result private.';if(p.purpose==='WAKE')return'Private setup: roll the d12 for your next Burrow Hour. Your wake hours must be different. Keep the result private.';if(p.purpose==='RAIDER_TIE')return'Private setup: tied earliest Bandits need a private d6 tiebreak. Lowest unique result becomes the historical Raider. Keep the roll private.';if(p.purpose==='HUNTER_CONVERSION')return'Private turn: a starting Bandit overlaps this Hunter wake. Roll the d6. One or two converts you to the Bandit side. Keep the result secret.';return'Private turn: complete the private roll requested by Ferret Frenzy and do not announce the result.'}
if(p.kind==='ACTION'){switch(p.type){case'SNUGGLER_BOND':return'Private setup, Snuggler: choose two different other players and lock the Snuggle Bond. Do not announce the pair.';case'DOOKER_GLIMPSE':return'Private turn, Dooker: choose one other player for your Glimpse, or pass. It reports current allegiance at this exact moment and can become stale later.';case'DOOKER_PEEK_HAMMOCK':return'Private turn, Dooker: inspect exactly one face-down Hammock card. Remember it privately; the game will then offer the optional Trip.';case'DOOKER_TRIP':return'Private turn, Dooker: you may place the Hammock card you saw onto one other player, exchanging their Current Card, or pass. You do not see the displaced card.';case'TROUBLE_SWAP':return'Private turn, Trouble: choose two different other players. Their Current Cards swap blindly; you do not inspect either card.';case'BUSINESS_INSPECT':return'Private turn, Business: because you woke alone, you may inspect exactly one randomly selected wake result from one other player, or pass. This is not their whole schedule.';case'HUNTER_MARK':return'Private turn, Hunter: if you are still loyal, choose one other player for your Hunt Mark. It only has an effect if you are caught and the marked player is Bandit-aligned at resolution.';case'GUARDIAN_PROTECT':return'Private vote, Guardian: protect one other player before Paw Point resolves. Protection is separate from your own vote and remains secret until results.';default:return`Private turn, ${roleName(role)}: complete the action shown in Ferret Frenzy. Keep your choice and result private.`}}
if(p.kind==='VOTE'||(upper(game.phase)==='VOTE'&&!me.voteLocked))return'Private vote: choose one other player for Paw Point. Votes lock simultaneously. Do not reveal your actual selection before resolution.';return''}
function factText(f){const t=upper(f?.type);switch(t){case'ITCHY_CHECK':return f.activated?'Private result: Ears Up activated. You receive the additional d12 wake required by the game.':'Private result: Too Itchy. No additional wake activated.';case'HUNTER_CONVERSION':return f.converted?'Private result: Hunter converted. You are now Bandit-aligned. Keep this secret.':'Private result: Hunter did not convert. You remain loyal. Keep the result secret.';case'DOOKER_GLIMPSE':return`Private result: your Glimpse says ${f.displayName||'that player'} was ${f.result==='BANDIT_ALIGNED'?'Bandit-aligned':'not Bandit-aligned'} at that moment. Later movement can make this fact stale.`;case'DOOKER_HAMMOCK_PEEK':return`Private result: the Hammock card you inspected is ${roleName(f.role)}. Keep the card and slot secret.`;case'BUSINESS_WAKE_INSPECTION':{const h=Number(f.inspectedWakeHour||f.wakeHour||f.resultHour||f.result||0);return`Private result: ${f.displayName||'your chosen player'} has the inspected wake result${h?` Hour ${h}`:''}. You did not learn their whole schedule.`}case'TROUBLE_CONVERTED':return`Private result: you became In On It during the theft window${f.raiderDisplayName||f.raiderName?` and learned the historical Raider is ${f.raiderDisplayName||f.raiderName}`:''}. Keep it secret.`;case'TROUBLE_SWAP':return'Private result: your blind Current Card swap is complete. Starting Roles and role actions did not move.';case'DOOKER_TRIP':return`Private result: your Trip placed the known Hammock card with ${f.displayName||'your target'}. The displaced card stayed hidden from you.`;case'HUNT_MARK':return`Private result: your Hunt Mark is set on ${f.displayName||'your chosen player'}.`;case'GUARDIAN_PROTECTION':return`Private result: protection is locked on ${f.displayName||'your chosen player'}.`;case'GUARDIAN_RECOGNITION':case'HUNTER_RECOGNITION':return`Private setup fact: you recognize ${f.displayName||'your counterpart'} as your starting Hunter/Guardian counterpart. This does not prove Hunter's later allegiance.`;case'BANDIT_ROSTER':return`Private setup fact: the starting Bandit roster is ${namesForIds((f.participants||[]).map(p=>p.participantId))}.`;case'RAIDER_IDENTITY':return`Private fact: the historical Raider is ${f.displayName||f.participantId||'the identified player'}.`;case'ITCHY_PARTIAL_CLUE':{const names=(f.candidates||[]).map(p=>p.displayName||participants().find(x=>String(x.id)===String(p.participantId))?.displayName||p.participantId).filter(Boolean);return f.degraded===true||names.length!==2?`Private degraded Itchy clue: ${names.join(' / ')||'no valid two-player candidate pair could be formed'}.`:`Private result: exactly one of these two is the historical Raider: ${names.join(' / ')}. The other is a decoy.`}case'ITCHY_TIMING_CLUE':return`Private degraded Itchy timing clue: the raid occurred in ${f.range==='HOURS_1_6'?'Hours 1 through 6':'Hours 7 through 12'}.`;default:return''}}
function publicLine(game,results){switch(upper(game.phase)){case'LOBBY':return'The burrow is open. Finish getting ready, then the host can begin the round.';case'PREP':return'Pre-Game Setup is underway. Complete only the private roll or setup action shown on your own Ferret Frenzy screen.';case'NIGHT':return`Burrow Hour ${Number(game.currentHour)||1}. Stay quiet and follow only the private instruction on your own screen. No player role or hidden action is being announced.`;case'MORNING':return'Morning Business begins. The Minnow Treats are missing. Compare wake hours, Treat State, co-wakers, card movement, and claims. Narrator messages do not verify anyone\'s story.';case'VOTE':return'Paw Point is open. Keep discussing, then lock one private vote. Guardian protection resolves separately before capture eligibility, and tied eligible leaders can all be caught.';case'RESULTS':{if(!results)return'The round is complete. Check the public result screen.';const caught=namesForIds(results.caughtParticipantIds||results.caught||[]),winner=upper(results.primaryWinner)==='BUSINESS'?'Business caught the historical Raider. The Business side wins.':'The historical Raider escaped the final valid catch. The Bandit side wins.';return`Round results. ${winner} Caught: ${caught||'none'}. Bond-Revealed players are reveal-only unless separately listed as caught.`}default:return'The Ferret Frenzy round changed phase. Check the game screen for the current step.'}}
function loadSentKeys(gameId){const k=`ff:narrator-chat-sent:${gameId||'unknown'}`;if(k===state.chatStoreKey)return;state.chatStoreKey=k;try{const arr=JSON.parse(localStorage.getItem(k)||'[]');state.sentChatKeys=new Set(Array.isArray(arr)?arr.slice(-100):[])}catch{state.sentChatKeys=new Set()}}
function rememberSentKey(key){if(!key)return;state.sentChatKeys.add(key);try{localStorage.setItem(state.chatStoreKey,JSON.stringify([...state.sentChatKeys].slice(-100)))}catch{}}
async function postNarratorChat(line,key='',channel='narrator'){if(!isHost())throw new Error('Only the host narrator posts shared narrator chat, preventing duplicate narrator messages.');if(!canChatPhase())throw new Error('Shared chat is not open in this phase.');if(key&&state.sentChatKeys.has(key))return false;const fn=window.FFNetwork?.sendNarratorChat;if(!fn)throw new Error('Narrator chat bridge is not ready.');const sent=await fn(line,{channel});if(sent===false){setTimeout(()=>postNarratorChat(line,key,channel).catch(err=>setStatus(`Narrator chat retry failed: ${err.message}`,true)),700);return false}rememberSentKey(key);setStatus(`Narrator posted in #${channel}.`);return true}
function process(s){if(!s?.game||state.processing)return;state.processing=true;try{state.current=s;const game=s.game||{},me=s.me||{};loadSentKeys(game.id||game.code);ui.phase.textContent=cap(game.phase||'Waiting');ui.hour.textContent=upper(game.phase)==='NIGHT'?String(game.currentHour||1):'—';ui.seat.textContent=me.displayName||'Connected player';const host=isHost();ui.autoChat.disabled=!host;ui.chatInput.disabled=!host||!canChatPhase();ui.chatSend.disabled=!host||!canChatPhase();if(ui.chatChannel)ui.chatChannel.disabled=!host;ui.sendCurrent.disabled=state.lastKind!=='shared'||!host||!canChatPhase();if(!host)ui.autoChat.checked=false;const prompt=me.actionPrompt||{},promptKey=[game.phase,game.currentHour,prompt.kind,prompt.type,prompt.purpose,me.voteLocked?'locked':''].join('|'),phaseKey=[game.id||game.code,game.phase,upper(game.phase)==='NIGHT'?game.currentHour:'',s.results?.primaryWinner||''].join('|');if(phaseKey!==state.lastPublicKey){state.lastPublicKey=phaseKey;say(publicLine(game,s.results),'shared',phaseKey)}if(promptKey!==state.lastPromptKey){state.lastPromptKey=promptKey;const line=privatePrompt(game,me);if(line)say(line,'private')}const facts=me.privateFacts||[];if(!state.factsSeeded){facts.forEach(f=>state.lastFactKeys.add(JSON.stringify(f)));state.factsSeeded=true}else facts.forEach(f=>{const key=JSON.stringify(f);if(state.lastFactKeys.has(key))return;state.lastFactKeys.add(key);const line=factText(f);if(line)say(line,'private')});setStatus(host?'Narrator attached to this host seat. Shared narrator chat is available in public channels.':'Narrator attached to this player seat. Private lines stay local; the host narrator owns shared chat posting.')}finally{state.processing=false}}
function tick(){const s=window.FFNetwork?.getState?.();if(s)process(s);else setStatus('Waiting for the existing Ferret Frenzy player session…')}
ui.repeat.addEventListener('click',()=>{if(state.lastSpoken&&(state.lastKind!=='private'||ui.headphones.checked))speak(state.lastSpoken)});
ui.pause.addEventListener('click',()=>{state.paused=!state.paused;ui.pause.textContent=state.paused?'Resume narrator':'Pause narrator';if(state.paused&&'speechSynthesis'in window)window.speechSynthesis.cancel()});
ui.stop.addEventListener('click',()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel()});
ui.test.addEventListener('click',()=>speak('The burrow is stirring. Listen for your turn, then follow the instruction on your own game screen.'));
ui.clearLog.addEventListener('click',()=>{ui.log.innerHTML='<li class="narrator-empty">Nothing narrated yet.</li>'});
ui.headphones.addEventListener('change',()=>{if(ui.headphones.checked)setStatus('Private speech enabled on this device. Confirm the selected audio output is actually private.')});
ui.sendCurrent.addEventListener('click',()=>{if(state.lastKind==='shared')postNarratorChat(state.lastShared,state.lastSharedKey,ui.chatChannel?.value||'narrator').catch(err=>setStatus(err.message,true))});
ui.chatForm.addEventListener('submit',e=>{e.preventDefault();const line=ui.chatInput.value.trim();if(!line)return;postNarratorChat(line,`manual:${Date.now()}`,ui.chatChannel?.value||'narrator').then(()=>{ui.chatInput.value=''}).catch(err=>setStatus(err.message,true))});
addEventListener('ff-audio-level',e=>syncSound(e.detail?.level));
addEventListener('ferret-frenzy-action',e=>{if(e.detail?.type==='soundLevel')syncSound(e.detail.level)});
if('speechSynthesis'in window){loadVoices();window.speechSynthesis.onvoiceschanged=loadVoices}else syncSound();
window.FFNarrator={marker:MARKER,process,say,speak,getState:()=>state,syncSound};
setInterval(tick,500);tick();
})();
